### ISSUE TITLE
Could not broadcast input array from shape (127,127,4) into shape (127,0,4)

### ISSUE THREAD

**Issue by rajeshchiplogictech** [ojoaobrito/ExplainablePR#2]
Hello,

Getting this error while Recognising and explaining a test pair.

File "add_interpretable_colour.py", line 135, in <module>
    explanation[38:37 + IMAGE_SIZE, 422:(422 + (IMAGE_SIZE - 1)), :] = coloured_explanation_B
ValueError: could not broadcast input array from shape (127,127,4) into shape (127,0,4)

**Comment by ojoaobrito** [comment]
Hello! Hope you are doing well!

**Comment by ojoaobrito** [comment]
I see, have you changed the `NUM_IMAGES` variables in `inference/code/stylegan2/generate_synthetic_dataset.py`? I'm asking because at the end of that file, the generated samples' names are filled with zeros to match the length of the `NUM_IMAGES` variables. So, for example, if you set it to 1000, the `.npy` files will have names like "0000_(...).npy", "0001_(...).npy", etc... With that being said, `001_R_R.npy` should really be called `0001_R_R.npy`. A problem like this one can easily propagate forward and lead to errors in subsequent steps.

**Comment by rajeshchiplogictech** [comment]
> I see, have you changed the `NUM_IMAGES` variables in `inference/code/stylegan2/generate_synthetic_dataset.py`? I'm asking because at the end of that file, the generated samples' names are filled with zeros to match the length of the `NUM_IMAGES` variables. So, for example, if you set it to 1000, the `.npy` files will have names like "0000_(...).npy", "0001_(...).npy", etc... With that being said, `001_R_R.npy` should really be called `0001_R_R.npy`. A problem like this one can easily propagate forward and lead to errors in subsequent steps.

yes, i changed NUM_IMAGES =1000 in inference/code/stylegan2/generate_synthetic_dataset.py and also in inference/code/stylegan2/get_segmentation_maps.py

**Comment by ojoaobrito** [comment]
The 2nd step generates segmentation masks for the irises and eyebrows, but if it can't do that for some image(s) (e.g., the Mask R-CNN model fails to predict masks), it will remove said image(s). To explain a pair we need both the synthetic images and their corresponding masks. So, if you need 1000 fully ready synthetic images (and masks), you'll need to set the `NUM_IMAGES ` variable to a number that's a little higher than 1000, to compensate for the images that end up being removed. Alternatively, you can tweak the code so that these two steps are in the same script and while loop (generation of a synthetic pair and prediction of the corresponding masks) and check whether you've hit your target (e.g., 1000).

**Comment by rajeshchiplogictech** [comment]
> The 2nd step generates segmentation masks for the irises and eyebrows, but if it can't do that for some image(s) (e.g., the Mask R-CNN model fails to predict masks), it will remove said image(s). To explain a pair we need both the synthetic images and their corresponding masks. So, if you need 1000 fully ready synthetic images (and masks), you'll need to set the `NUM_IMAGES ` variable to a number that's a little higher than 1000, to compensate for the images that end up being removed. Alternatively, you can tweak the code so that these two steps are in the same script and while loop (generation of a synthetic pair and prediction of the corresponding masks) and check whether you've hit your target (e.g., 1000).

I tried to increase the NUM_IMAGES in 2nd steps. but getting same issue. it will remove images in said folder.

**Comment by ojoaobrito** [comment]
Perhaps you could try combining the two scripts into one. Using a while loop, you could generate synthetic data and immediately predict masks for it. If unsuccessful, remove the generated data and move to the next iteration. Repeat this process until you've achieved the desired amount of data. It should fix the issue you're having and ensure that you don't come across any errors past this point.

**Comment by rajeshchiplogictech** [comment]
Getting this error on 4th steps

Traceback (most recent call last):
  File "assemble_explanation.py", line 114, in <module>
    assemble_explanation(image_A, image_B, difference_mask_1, difference_mask_2, score, genuine_or_impostor)
  File "assemble_explanation.py", line 75, in assemble_explanation
    final_img = Image.fromarray(final_img.astype(np.uint8))
AttributeError: 'Image' object has no attribute 'astype'

**Comment by ojoaobrito** [comment]
I believe it is due to the fact that `final_img` is a PIL object, instead of a NumPy array, as intended. An easy fix would be to cast it into an array with `np.asarray(final_img)` and then calling `astype`. Or you could just skip that line entirely, because its purpose is to convert an array into a PIL image, but I guess that's already the case.

**Comment by rajeshchiplogictech** [comment]
> np.asarray(final_img)

thanks, its working. but now getting this error.

Traceback (most recent call last):
  File "add_interpretable_colour.py", line 122, in <module>
    coloured_explanation_B = add_interpretable_colour(explanation_B, image_B)
  File "add_interpretable_colour.py", line 90, in add_interpretable_colour
    white_template = Image.fromarray((np.ones((coloured_explanation_img.shape[0], coloured_explanation_img.shape[1], 3), int) * 255).astype(np.uint8))
AttributeError: 'Image' object has no attribute 'shape'

**Comment by ojoaobrito** [comment]
Now it seems that you have to do the opposite (`coloured_explanation_img` is a PIL object when it should be an array). So you could just do: `coloured_explanation_img = np.asarray(coloured_explanation_img)`.

**Comment by rajeshchiplogictech** [comment]
> 



> Now it seems that you have to do the opposite (`coloured_explanation_img` is a PIL object when it should be an array). So you could just do: `coloured_explanation_img = np.asarray(coloured_explanation_img)`.

when i did coloured_explanation_img = np.asarray(coloured_explanation_img)  above this line white_template = Image.fromarray((np.ones((coloured_explanation_img.shape[0], coloured_explanation_img.shape[1], 3), int) * 255).astype(np.uint8)). i m getting IndexError: tuple index out of range error.

Traceback (most recent call last):
  File "add_interpretable_colour.py", line 126, in <module>
    coloured_explanation_B = add_interpretable_colour(explanation_B, image_B)
  File "add_interpretable_colour.py", line 94, in add_interpretable_colour
    white_template = Image.fromarray((np.ones((coloured_explanation_img.shape[0], coloured_explanation_img.shape[1], 3), int) * 255).astype(np.uint8))
IndexError: tuple index out of range


when i print the shape of coloured_explanation_img, i m getting blank.

**Comment by ojoaobrito** [comment]
It is very strange because you are getting errors that I haven't met before. Maybe you've changed one or two lines at the start and it is being exponentiated across subsequent steps / scripts.

**Comment by rajeshchiplogictech** [comment]
No, i just changed NUM_IMAGES=100 in generate_synthetic_dataset.py file only, other code is same.

**Comment by ojoaobrito** [comment]
I really do not know what else to say, if everything is properly installed and the code hasn't been modified, it has no reason to fail. I tested it myself and all went well.

**Comment by rajeshchiplogictech** [comment]
after completing 2nd steps(Segmenting the synthetic dataset), i can see image_1 folder empty. but in segmentation_maps_1 folder i can see many sub folder and its include eyebrow_A.png,eyebrow_B.png,iris_A.png,iris_B.png. so is this correct or image_1 folder also must have data?

**Comment by ojoaobrito** [comment]
Ideally, `image_1` would have data too. If you don't have masks for every synthetic image you've generated, then you have to look into that. If you can guarantee this, then I can assure you that the code runs and functions as intended.

**Comment by rajeshchiplogictech** [comment]
can you explain me this line?
os.rename("synthetic_dataset_" + GENUINE_OR_IMPOSTOR + "/images_" + str(SCRIPT_ID) + "/" + i, "synthetic_dataset_" + GENUINE_OR_IMPOSTOR + "/images_revised_" + str(SCRIPT_ID) + "/" + i)

becuase of this line, the data in image_1 folder is removed.

**Comment by ojoaobrito** [comment]
Hi there!

The `images_1` folder is temporary, meaning that the final masks will go into the `images_revised_1` folder (the one where the masks are correct and complete). I believe I ended up deleting `images_1` and renaming `images_revised_1` to `images_1`. A simple line in the code should be able to do something similar.

**Comment by rajeshchiplogictech** [comment]
EXPLAINING THE GIVEN PAIR...
[INFO] USING SEGMENTATION DATA!

SEGMENTING THE GIVEN PAIR...
DONE SEGMENTING THE GIVEN PAIR!
C_C

FINDING NEIGHBOURS...
find_neri_master args ['find_neighbours_master.py', '128', 'True', '15', 'elementwise_comparison', 'resnet18', '../../trained_models/resnet_18/models/resnet_18.pt', 'IoU', 'True', 'C_C']
num_slaves 7
distances []
Traceback (most recent call last):
  File "find_neighbours_master.py", line 208, in <module>
    slave_distances = np.load("results/" + distances[i])
IndexError: list index out of range
ERROR FOUND, STOPPING NOW...



can you look into this error? i m facing this issue while running explait_pair.py

**Comment by rajeshchiplogictech** [comment]
![aee](https://user-images.githubusercontent.com/87691063/172347200-ffc04d3d-bb84-4d7c-9432-440b608d149f.png)

previous error is resolved now.

getting this error
Traceback (most recent call last):
  File "find_neighbours_master.py", line 274, in <module>
    best_neighbours_names_final_list.append(names[best_neighbours_names[i]])
IndexError: list index out of range
ERROR FOUND, STOPPING NOW...

i checked neighbour_names.txt file. and its showing empty.

**Comment by ojoaobrito** [comment]
Perhaps you haven't generated enough data, it seems that there are no synthetic pais with both irises in the middle and two images from the right side of the face. As you can see, other configurations (such as right oriented irises and two images from the left side of the face) are available in the synthetic dataset.

**Comment by ojoaobrito** [comment]
My suggestion would be to try with a much bigger synthetic dataset. My implementation contemplated at least 100K synthetic pairs and that was partly because more pairs bring more variety (which is what you are lacking, as far as I can see). If there are no possible matches, it will fail like it did to you.

**Comment by rajeshchiplogictech** [comment]
do you have pretrained model for this? i just want to verify, if it satisfies our requirement . i m trying with 100k images. but its taking lots of time even on GPU. Thanks

**Comment by ojoaobrito** [comment]
Hello!

All trained models are in this OneDrive folder: https://deepneuronic-my.sharepoint.com/personal/joao_brito_deepneuronic_com/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fjoao%5Fbrito%5Fdeepneuronic%5Fcom%2FDocuments%2FBrito%2FExplainablePR.

**Comment by ojoaobrito** [comment]
Okay, what about through this link instead: https://deepneuronic-my.sharepoint.com/:f:/p/joao_brito/Ev8v03PFj_lFnsHojPv7kR4BgpZRtBeks5t49CytIub4lA?e=98dJ3P ?

**Comment by rajeshchiplogictech** [comment]
yes, that i can access it. but i need synthetic dataset. so i can skip Inference steps.

**Comment by ojoaobrito** [comment]
Unfortunately, I do not have any synthetic dataset. This repository was created a while ago and I've moved on to new projects. The synthetic dataset took a good chunk of storage space and I discarded it, given that I still had the pre-trained models and could synthesise a new dataset if needed. Making it available in a cloud storage provider (OneDrive, Google Drive, etc...) would be impractical and costly.

**Comment by rajeshchiplogictech** [comment]
Hello,

how can i start Segmenting the synthetic dataset on the GPU?
![gggg](https://user-images.githubusercontent.com/87691063/173052781-8c1fc75b-de71-42ff-92e9-fb9c5fb94b32.png)

i checked the GPU usages again and find that there is no  any running process for GPU. but currently i completed more than 3k images and its continuing. but gpu didnt show me any process.

i print this line in the server 
device = torch.device("cuda:0" if(torch.cuda.is_available()) else "cpu")

and its giving me "cuda:0" result.

**Comment by ojoaobrito** [comment]
Hi there!

I see. Do you also have cudNN properly installed? Some scripts use Tensorflow and it needs that setup to make use of your GPU.

**Comment by rajeshchiplogictech** [comment]
Hi,

when i run the generate_synthetic_dataset.py. it will run on the GPU but get_segmentation_maps.py is not running on the GPU.

i checked the code and find that below is the line for checking gpu availability.
device = torch.device("cuda:0" if(torch.cuda.is_available()) else "cpu")

but after checking gpu availability, the device variable didnt used anywhere. so is it the reason for not using the GPU? if yes, then let me know when i use this variable?

**Comment by ojoaobrito** [comment]
Closing issue due to lack of activity.
